
for %%m in (flash sram libsdl libmw librtos) do (
    for %%c in (cm0plus cm4 cm7 cm7_0 cm7_1) do (
        
        rmdir /Q /S %%m\%%c\objs
        del   /Q    %%m\%%c\*.elf
        del   /Q    %%m\%%c\*.dep
        del   /Q    %%m\%%c\*.dla
        del   /Q    %%m\%%c\*.dnm
        del   /Q    %%m\%%c\*.map
        del   /Q    %%m\%%c\*.srec
        del   /Q    %%m\%%c\*.a
        del   /Q    %%m\%%c\*.dba        
        
    )
)


for %%m in (libcrypto) do (
    for %%t in (client server) do (
        for %%c in (cm0plus cm4 cm7 cm7_0 cm7_1) do (
        
            rmdir /Q /S %%m\%%t\%%c\objs
        )
    )
)

::=========================================================================
:: Following clean commands are needed if project is used in combination
:: with the Traveo II MCAL Sample Project

:: Following files/folders are generated by scripts, so all can be deleted
rmdir /Q /S libmcal
del   /Q    mcal_dependency.file
del   /Q    options_mcal.opt
del   /Q    tvii*_common_generated.gpj

:: Files/folders below are build output from GHS
rmdir /Q /S libstubs
