/***************************************************************************//**
* \file cyreg_smif.h
*
* \brief
* SMIF register definition header
*
* \note
* Generator version: 1.6.0.453
* Database revision: TVIIC2D6MDDR_A0_CMR2
*
********************************************************************************
* \copyright
* Copyright 2016-2021, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#ifndef _CYREG_SMIF_H_
#define _CYREG_SMIF_H_

#include "cyip_smif_v4.h"

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION0)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION0_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401000UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION0_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401010UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION0_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401014UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION0_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401018UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION0_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040101CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION1)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION1_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401100UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION1_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401110UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION1_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401114UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION1_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401118UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION1_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040111CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION2)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION2_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401200UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION2_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401210UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION2_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401214UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION2_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401218UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION2_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040121CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION3)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION3_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401300UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION3_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401310UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION3_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401314UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION3_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401318UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION3_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040131CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION4)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION4_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401400UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION4_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401410UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION4_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401414UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION4_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401418UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION4_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040141CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION5)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION5_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401500UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION5_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401510UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION5_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401514UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION5_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401518UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION5_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040151CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION6)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION6_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401600UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION6_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401610UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION6_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401614UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION6_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401618UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION6_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040161CUL)

/**
  * \brief 'Remap regions' which define how XIP accesses can be remapped into SMIF physical spaces (SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION7)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION7_CTL ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_CTL_t*) 0x40401700UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION7_ADDR ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_ADDR_t*) 0x40401710UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION7_MASK ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_MASK_t*) 0x40401714UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION7_SMIF0_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF0_REMAP_t*) 0x40401718UL)
#define CYREG_SMIF0_SMIF_BRIDGE_SMIF_REMAP_REGION7_SMIF1_REMAP ((volatile un_SMIF_SMIF_BRIDGE_SMIF_REMAP_REGION_SMIF1_REMAP_t*) 0x4040171CUL)

/**
  * \brief AXI/AHB interleaving and FOTA bridge (SMIF_SMIF_BRIDGE0)
  */
#define CYREG_SMIF0_SMIF_BRIDGE_CTL     ((volatile un_SMIF_SMIF_BRIDGE_CTL_t*) 0x40400000UL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO0)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420200UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420204UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420208UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042020CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40420220UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40420224UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40420228UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4042022CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40420240UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40420244UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40420248UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4042024CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40420260UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40420264UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40420268UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO0_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4042026CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO1)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420280UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420284UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420288UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042028CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404202A0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404202A4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404202A8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404202ACUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404202C0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404202C4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404202C8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404202CCUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404202E0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404202E4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404202E8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO1_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404202ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO2)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420300UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420304UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420308UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042030CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40420320UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40420324UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40420328UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4042032CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40420340UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40420344UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40420348UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4042034CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40420360UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40420364UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40420368UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO2_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4042036CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO3)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420380UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420384UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420388UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042038CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404203A0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404203A4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404203A8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404203ACUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404203C0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404203C4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404203C8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404203CCUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404203E0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404203E4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404203E8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO3_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404203ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO4)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420400UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420404UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420408UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042040CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40420420UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40420424UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40420428UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4042042CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40420440UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40420444UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40420448UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4042044CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40420460UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40420464UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40420468UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO4_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4042046CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO5)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420480UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420484UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420488UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042048CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404204A0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404204A4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404204A8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404204ACUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404204C0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404204C4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404204C8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404204CCUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404204E0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404204E4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404204E8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO5_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404204ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO6)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420500UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420504UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420508UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042050CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40420520UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40420524UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40420528UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4042052CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40420540UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40420544UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40420548UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4042054CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40420560UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40420564UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40420568UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO6_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4042056CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO7)
  */
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40420580UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40420584UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40420588UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4042058CUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404205A0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404205A4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404205A8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404205ACUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404205C0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404205C4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404205C8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404205CCUL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404205E0UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404205E4UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404205E8UL)
#define CYREG_SMIF0_CORE0_SMIF_CRYPTO7_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404205ECUL)

/**
  * \brief Device (only used for XIP acceses) (SMIF_CORE_DEVICE0)
  */
#define CYREG_SMIF0_CORE0_DEVICE0_CTL   ((volatile un_SMIF_CORE_DEVICE_CTL_t*) 0x40420800UL)
#define CYREG_SMIF0_CORE0_DEVICE0_ADDR  ((volatile un_SMIF_CORE_DEVICE_ADDR_t*) 0x40420808UL)
#define CYREG_SMIF0_CORE0_DEVICE0_MASK  ((volatile un_SMIF_CORE_DEVICE_MASK_t*) 0x4042080CUL)
#define CYREG_SMIF0_CORE0_DEVICE0_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_ADDR_CTL_t*) 0x40420820UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RX_CAPTURE_CONFIG ((volatile un_SMIF_CORE_DEVICE_RX_CAPTURE_CONFIG_t*) 0x40420828UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_RD_CMD_CTL_t*) 0x40420840UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_RD_ADDR_CTL_t*) 0x40420844UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_RD_MODE_CTL_t*) 0x40420848UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DUMMY_CTL_t*) 0x4042084CUL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DATA_CTL_t*) 0x40420850UL)
#define CYREG_SMIF0_CORE0_DEVICE0_RD_BOUND_CTL ((volatile un_SMIF_CORE_DEVICE_RD_BOUND_CTL_t*) 0x40420858UL)
#define CYREG_SMIF0_CORE0_DEVICE0_WR_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_WR_CMD_CTL_t*) 0x40420860UL)
#define CYREG_SMIF0_CORE0_DEVICE0_WR_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_WR_ADDR_CTL_t*) 0x40420864UL)
#define CYREG_SMIF0_CORE0_DEVICE0_WR_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_WR_MODE_CTL_t*) 0x40420868UL)
#define CYREG_SMIF0_CORE0_DEVICE0_WR_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DUMMY_CTL_t*) 0x4042086CUL)
#define CYREG_SMIF0_CORE0_DEVICE0_WR_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DATA_CTL_t*) 0x40420870UL)

/**
  * \brief Device (only used for XIP acceses) (SMIF_CORE_DEVICE1)
  */
#define CYREG_SMIF0_CORE0_DEVICE1_CTL   ((volatile un_SMIF_CORE_DEVICE_CTL_t*) 0x40420880UL)
#define CYREG_SMIF0_CORE0_DEVICE1_ADDR  ((volatile un_SMIF_CORE_DEVICE_ADDR_t*) 0x40420888UL)
#define CYREG_SMIF0_CORE0_DEVICE1_MASK  ((volatile un_SMIF_CORE_DEVICE_MASK_t*) 0x4042088CUL)
#define CYREG_SMIF0_CORE0_DEVICE1_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_ADDR_CTL_t*) 0x404208A0UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RX_CAPTURE_CONFIG ((volatile un_SMIF_CORE_DEVICE_RX_CAPTURE_CONFIG_t*) 0x404208A8UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_RD_CMD_CTL_t*) 0x404208C0UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_RD_ADDR_CTL_t*) 0x404208C4UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_RD_MODE_CTL_t*) 0x404208C8UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DUMMY_CTL_t*) 0x404208CCUL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DATA_CTL_t*) 0x404208D0UL)
#define CYREG_SMIF0_CORE0_DEVICE1_RD_BOUND_CTL ((volatile un_SMIF_CORE_DEVICE_RD_BOUND_CTL_t*) 0x404208D8UL)
#define CYREG_SMIF0_CORE0_DEVICE1_WR_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_WR_CMD_CTL_t*) 0x404208E0UL)
#define CYREG_SMIF0_CORE0_DEVICE1_WR_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_WR_ADDR_CTL_t*) 0x404208E4UL)
#define CYREG_SMIF0_CORE0_DEVICE1_WR_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_WR_MODE_CTL_t*) 0x404208E8UL)
#define CYREG_SMIF0_CORE0_DEVICE1_WR_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DUMMY_CTL_t*) 0x404208ECUL)
#define CYREG_SMIF0_CORE0_DEVICE1_WR_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DATA_CTL_t*) 0x404208F0UL)

/**
  * \brief Serial Memory Interface (SMIF_CORE0)
  */
#define CYREG_SMIF0_CORE0_CTL           ((volatile un_SMIF_CORE_CTL_t*) 0x40420000UL)
#define CYREG_SMIF0_CORE0_STATUS        ((volatile un_SMIF_CORE_STATUS_t*) 0x40420004UL)
#define CYREG_SMIF0_CORE0_CTL2          ((volatile un_SMIF_CORE_CTL2_t*) 0x40420008UL)
#define CYREG_SMIF0_CORE0_DLP_DELAY_TAP_SEL0 ((volatile un_SMIF_CORE_DLP_DELAY_TAP_SEL0_t*) 0x40420010UL)
#define CYREG_SMIF0_CORE0_DLP_DELAY_TAP_SEL1 ((volatile un_SMIF_CORE_DLP_DELAY_TAP_SEL1_t*) 0x40420014UL)
#define CYREG_SMIF0_CORE0_DLP_CTL       ((volatile un_SMIF_CORE_DLP_CTL_t*) 0x40420018UL)
#define CYREG_SMIF0_CORE0_DLP_STATUS0   ((volatile un_SMIF_CORE_DLP_STATUS0_t*) 0x40420020UL)
#define CYREG_SMIF0_CORE0_DLP_STATUS1   ((volatile un_SMIF_CORE_DLP_STATUS1_t*) 0x40420024UL)
#define CYREG_SMIF0_CORE0_TX_CMD_FIFO_STATUS ((volatile un_SMIF_CORE_TX_CMD_FIFO_STATUS_t*) 0x40420044UL)
#define CYREG_SMIF0_CORE0_TX_CMD_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_TX_CMD_MMIO_FIFO_STATUS_t*) 0x40420048UL)
#define CYREG_SMIF0_CORE0_TX_CMD_MMIO_FIFO_WR ((volatile un_SMIF_CORE_TX_CMD_MMIO_FIFO_WR_t*) 0x40420050UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_CTL ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_CTL_t*) 0x40420080UL)
#define CYREG_SMIF0_CORE0_TX_DATA_FIFO_STATUS ((volatile un_SMIF_CORE_TX_DATA_FIFO_STATUS_t*) 0x40420084UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_STATUS_t*) 0x40420088UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_WR1 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR1_t*) 0x40420090UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_WR2 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR2_t*) 0x40420094UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_WR4 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR4_t*) 0x40420098UL)
#define CYREG_SMIF0_CORE0_TX_DATA_MMIO_FIFO_WR1ODD ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR1ODD_t*) 0x4042009CUL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_CTL ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_CTL_t*) 0x404200C0UL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_STATUS_t*) 0x404200C4UL)
#define CYREG_SMIF0_CORE0_RX_DATA_FIFO_STATUS ((volatile un_SMIF_CORE_RX_DATA_FIFO_STATUS_t*) 0x404200C8UL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_RD1 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD1_t*) 0x404200D0UL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_RD2 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD2_t*) 0x404200D4UL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_RD4 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD4_t*) 0x404200D8UL)
#define CYREG_SMIF0_CORE0_RX_DATA_MMIO_FIFO_RD1_SILENT ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD1_SILENT_t*) 0x404200E0UL)
#define CYREG_SMIF0_CORE0_SLOW_CA_CTL   ((volatile un_SMIF_CORE_SLOW_CA_CTL_t*) 0x40420100UL)
#define CYREG_SMIF0_CORE0_SLOW_CA_CMD   ((volatile un_SMIF_CORE_SLOW_CA_CMD_t*) 0x40420108UL)
#define CYREG_SMIF0_CORE0_INTR          ((volatile un_SMIF_CORE_INTR_t*) 0x404207C0UL)
#define CYREG_SMIF0_CORE0_INTR_SET      ((volatile un_SMIF_CORE_INTR_SET_t*) 0x404207C4UL)
#define CYREG_SMIF0_CORE0_INTR_MASK     ((volatile un_SMIF_CORE_INTR_MASK_t*) 0x404207C8UL)
#define CYREG_SMIF0_CORE0_INTR_MASKED   ((volatile un_SMIF_CORE_INTR_MASKED_t*) 0x404207CCUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO0)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430200UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430204UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430208UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043020CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40430220UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40430224UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40430228UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4043022CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40430240UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40430244UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40430248UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4043024CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40430260UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40430264UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40430268UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO0_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4043026CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO1)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430280UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430284UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430288UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043028CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404302A0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404302A4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404302A8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404302ACUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404302C0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404302C4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404302C8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404302CCUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404302E0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404302E4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404302E8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO1_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404302ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO2)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430300UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430304UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430308UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043030CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40430320UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40430324UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40430328UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4043032CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40430340UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40430344UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40430348UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4043034CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40430360UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40430364UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40430368UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO2_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4043036CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO3)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430380UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430384UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430388UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043038CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404303A0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404303A4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404303A8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404303ACUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404303C0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404303C4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404303C8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404303CCUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404303E0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404303E4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404303E8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO3_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404303ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO4)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430400UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430404UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430408UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043040CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40430420UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40430424UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40430428UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4043042CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40430440UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40430444UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40430448UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4043044CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40430460UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40430464UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40430468UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO4_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4043046CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO5)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430480UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430484UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430488UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043048CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404304A0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404304A4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404304A8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404304ACUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404304C0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404304C4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404304C8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404304CCUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404304E0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404304E4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404304E8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO5_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404304ECUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO6)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430500UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430504UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430508UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043050CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x40430520UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x40430524UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x40430528UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x4043052CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x40430540UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x40430544UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x40430548UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x4043054CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x40430560UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x40430564UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x40430568UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO6_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x4043056CUL)

/**
  * \brief Cryptography registers (one set for each key) (SMIF_CORE_SMIF_CRYPTO7)
  */
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_CMD ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_CMD_t*) 0x40430580UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_ADDR ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_ADDR_t*) 0x40430584UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_MASK ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_MASK_t*) 0x40430588UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_SUBREGION ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_SUBREGION_t*) 0x4043058CUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_INPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT0_t*) 0x404305A0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_INPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT1_t*) 0x404305A4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_INPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT2_t*) 0x404305A8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_INPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_INPUT3_t*) 0x404305ACUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_KEY0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY0_t*) 0x404305C0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_KEY1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY1_t*) 0x404305C4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_KEY2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY2_t*) 0x404305C8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_KEY3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_KEY3_t*) 0x404305CCUL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_OUTPUT0 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT0_t*) 0x404305E0UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_OUTPUT1 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT1_t*) 0x404305E4UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_OUTPUT2 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT2_t*) 0x404305E8UL)
#define CYREG_SMIF0_CORE1_SMIF_CRYPTO7_CRYPTO_OUTPUT3 ((volatile un_SMIF_CORE_SMIF_CRYPTO_CRYPTO_OUTPUT3_t*) 0x404305ECUL)

/**
  * \brief Device (only used for XIP acceses) (SMIF_CORE_DEVICE0)
  */
#define CYREG_SMIF0_CORE1_DEVICE0_CTL   ((volatile un_SMIF_CORE_DEVICE_CTL_t*) 0x40430800UL)
#define CYREG_SMIF0_CORE1_DEVICE0_ADDR  ((volatile un_SMIF_CORE_DEVICE_ADDR_t*) 0x40430808UL)
#define CYREG_SMIF0_CORE1_DEVICE0_MASK  ((volatile un_SMIF_CORE_DEVICE_MASK_t*) 0x4043080CUL)
#define CYREG_SMIF0_CORE1_DEVICE0_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_ADDR_CTL_t*) 0x40430820UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RX_CAPTURE_CONFIG ((volatile un_SMIF_CORE_DEVICE_RX_CAPTURE_CONFIG_t*) 0x40430828UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_RD_CMD_CTL_t*) 0x40430840UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_RD_ADDR_CTL_t*) 0x40430844UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_RD_MODE_CTL_t*) 0x40430848UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DUMMY_CTL_t*) 0x4043084CUL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DATA_CTL_t*) 0x40430850UL)
#define CYREG_SMIF0_CORE1_DEVICE0_RD_BOUND_CTL ((volatile un_SMIF_CORE_DEVICE_RD_BOUND_CTL_t*) 0x40430858UL)
#define CYREG_SMIF0_CORE1_DEVICE0_WR_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_WR_CMD_CTL_t*) 0x40430860UL)
#define CYREG_SMIF0_CORE1_DEVICE0_WR_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_WR_ADDR_CTL_t*) 0x40430864UL)
#define CYREG_SMIF0_CORE1_DEVICE0_WR_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_WR_MODE_CTL_t*) 0x40430868UL)
#define CYREG_SMIF0_CORE1_DEVICE0_WR_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DUMMY_CTL_t*) 0x4043086CUL)
#define CYREG_SMIF0_CORE1_DEVICE0_WR_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DATA_CTL_t*) 0x40430870UL)

/**
  * \brief Device (only used for XIP acceses) (SMIF_CORE_DEVICE1)
  */
#define CYREG_SMIF0_CORE1_DEVICE1_CTL   ((volatile un_SMIF_CORE_DEVICE_CTL_t*) 0x40430880UL)
#define CYREG_SMIF0_CORE1_DEVICE1_ADDR  ((volatile un_SMIF_CORE_DEVICE_ADDR_t*) 0x40430888UL)
#define CYREG_SMIF0_CORE1_DEVICE1_MASK  ((volatile un_SMIF_CORE_DEVICE_MASK_t*) 0x4043088CUL)
#define CYREG_SMIF0_CORE1_DEVICE1_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_ADDR_CTL_t*) 0x404308A0UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RX_CAPTURE_CONFIG ((volatile un_SMIF_CORE_DEVICE_RX_CAPTURE_CONFIG_t*) 0x404308A8UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_RD_CMD_CTL_t*) 0x404308C0UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_RD_ADDR_CTL_t*) 0x404308C4UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_RD_MODE_CTL_t*) 0x404308C8UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DUMMY_CTL_t*) 0x404308CCUL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_RD_DATA_CTL_t*) 0x404308D0UL)
#define CYREG_SMIF0_CORE1_DEVICE1_RD_BOUND_CTL ((volatile un_SMIF_CORE_DEVICE_RD_BOUND_CTL_t*) 0x404308D8UL)
#define CYREG_SMIF0_CORE1_DEVICE1_WR_CMD_CTL ((volatile un_SMIF_CORE_DEVICE_WR_CMD_CTL_t*) 0x404308E0UL)
#define CYREG_SMIF0_CORE1_DEVICE1_WR_ADDR_CTL ((volatile un_SMIF_CORE_DEVICE_WR_ADDR_CTL_t*) 0x404308E4UL)
#define CYREG_SMIF0_CORE1_DEVICE1_WR_MODE_CTL ((volatile un_SMIF_CORE_DEVICE_WR_MODE_CTL_t*) 0x404308E8UL)
#define CYREG_SMIF0_CORE1_DEVICE1_WR_DUMMY_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DUMMY_CTL_t*) 0x404308ECUL)
#define CYREG_SMIF0_CORE1_DEVICE1_WR_DATA_CTL ((volatile un_SMIF_CORE_DEVICE_WR_DATA_CTL_t*) 0x404308F0UL)

/**
  * \brief Serial Memory Interface (SMIF_CORE1)
  */
#define CYREG_SMIF0_CORE1_CTL           ((volatile un_SMIF_CORE_CTL_t*) 0x40430000UL)
#define CYREG_SMIF0_CORE1_STATUS        ((volatile un_SMIF_CORE_STATUS_t*) 0x40430004UL)
#define CYREG_SMIF0_CORE1_CTL2          ((volatile un_SMIF_CORE_CTL2_t*) 0x40430008UL)
#define CYREG_SMIF0_CORE1_DLP_DELAY_TAP_SEL0 ((volatile un_SMIF_CORE_DLP_DELAY_TAP_SEL0_t*) 0x40430010UL)
#define CYREG_SMIF0_CORE1_DLP_DELAY_TAP_SEL1 ((volatile un_SMIF_CORE_DLP_DELAY_TAP_SEL1_t*) 0x40430014UL)
#define CYREG_SMIF0_CORE1_DLP_CTL       ((volatile un_SMIF_CORE_DLP_CTL_t*) 0x40430018UL)
#define CYREG_SMIF0_CORE1_DLP_STATUS0   ((volatile un_SMIF_CORE_DLP_STATUS0_t*) 0x40430020UL)
#define CYREG_SMIF0_CORE1_DLP_STATUS1   ((volatile un_SMIF_CORE_DLP_STATUS1_t*) 0x40430024UL)
#define CYREG_SMIF0_CORE1_TX_CMD_FIFO_STATUS ((volatile un_SMIF_CORE_TX_CMD_FIFO_STATUS_t*) 0x40430044UL)
#define CYREG_SMIF0_CORE1_TX_CMD_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_TX_CMD_MMIO_FIFO_STATUS_t*) 0x40430048UL)
#define CYREG_SMIF0_CORE1_TX_CMD_MMIO_FIFO_WR ((volatile un_SMIF_CORE_TX_CMD_MMIO_FIFO_WR_t*) 0x40430050UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_CTL ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_CTL_t*) 0x40430080UL)
#define CYREG_SMIF0_CORE1_TX_DATA_FIFO_STATUS ((volatile un_SMIF_CORE_TX_DATA_FIFO_STATUS_t*) 0x40430084UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_STATUS_t*) 0x40430088UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_WR1 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR1_t*) 0x40430090UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_WR2 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR2_t*) 0x40430094UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_WR4 ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR4_t*) 0x40430098UL)
#define CYREG_SMIF0_CORE1_TX_DATA_MMIO_FIFO_WR1ODD ((volatile un_SMIF_CORE_TX_DATA_MMIO_FIFO_WR1ODD_t*) 0x4043009CUL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_CTL ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_CTL_t*) 0x404300C0UL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_STATUS ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_STATUS_t*) 0x404300C4UL)
#define CYREG_SMIF0_CORE1_RX_DATA_FIFO_STATUS ((volatile un_SMIF_CORE_RX_DATA_FIFO_STATUS_t*) 0x404300C8UL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_RD1 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD1_t*) 0x404300D0UL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_RD2 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD2_t*) 0x404300D4UL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_RD4 ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD4_t*) 0x404300D8UL)
#define CYREG_SMIF0_CORE1_RX_DATA_MMIO_FIFO_RD1_SILENT ((volatile un_SMIF_CORE_RX_DATA_MMIO_FIFO_RD1_SILENT_t*) 0x404300E0UL)
#define CYREG_SMIF0_CORE1_SLOW_CA_CTL   ((volatile un_SMIF_CORE_SLOW_CA_CTL_t*) 0x40430100UL)
#define CYREG_SMIF0_CORE1_SLOW_CA_CMD   ((volatile un_SMIF_CORE_SLOW_CA_CMD_t*) 0x40430108UL)
#define CYREG_SMIF0_CORE1_INTR          ((volatile un_SMIF_CORE_INTR_t*) 0x404307C0UL)
#define CYREG_SMIF0_CORE1_INTR_SET      ((volatile un_SMIF_CORE_INTR_SET_t*) 0x404307C4UL)
#define CYREG_SMIF0_CORE1_INTR_MASK     ((volatile un_SMIF_CORE_INTR_MASK_t*) 0x404307C8UL)
#define CYREG_SMIF0_CORE1_INTR_MASKED   ((volatile un_SMIF_CORE_INTR_MASKED_t*) 0x404307CCUL)

#endif /* _CYREG_SMIF_H_ */


/* [] END OF FILE */
