/***************************************************************************//**
* \file main_cm0plus.c
*
* \version 1.0
*
* \brief Main example file for CM0+
*
********************************************************************************
* \copyright
* Copyright 2016-2020, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "cy_project.h"
#include "cy_device_headers.h"

/* Macro for user LED */
#if (CY_USE_PSVP == 1) 
    #define USER_LED_PORT               CY_LED0_PORT
    #define USER_LED_PIN                CY_LED0_PIN
    #define USER_LED_PIN_MUX            CY_LED0_PIN_MUX
#else
    #define USER_LED_PORT               CY_CB_LED_PORT
    #define USER_LED_PIN                CY_CB_LED_PIN
    #define USER_LED_PIN_MUX            CY_CB_LED_PIN_MUX 
#endif

/* Macro for SRAM definition */
#define RAM_0_ADDRESS                   (0x08000800)
#define RAM_0_DATA                      (0x5A5A5A5A)
#define RAM_0_MASK_VALUE                (0x00FFFFFFU)
#define RAM_0_CORRECT_PARITY            (0x6E)
#define RAM_0_ONEBIT_PARITY             (0x6F)
#define RAM_0_TWOBIT_PARITY             (0x6D)


/* Structure definition for io port pin initialization */
cy_stc_gpio_pin_config_t user_led_port_pin_cfg =             
{                                                  
    .outVal = 0x00,                                
    .driveMode = CY_GPIO_DM_STRONG_IN_OFF,    
    .hsiom = USER_LED_PIN_MUX,                           
    .intEdge = 0,                                  
    .intMask = 0,                                  
    .vtrip = 0,                                    
    .slewRate = 0,                                 
    .driveSel = 0,                                 
    .vregEn = 0,                                   
    .ibufMode = 0,                                 
    .vtripSel = 0,                                 
    .vrefSel = 0,                                  
    .vohSel = 0,                                   
};

/* global variable definition */
uint8_t isr_triggered = 0;
uint32_t faultData0, faultData1, faultData2, faultData3;
cy_en_sysflt_source_t fault_source;
uint32_t fail = 0;
    
/* Fault 0 interrupt handler */
void irqFaultReport0Handler(void)
{
    isr_triggered = 1;
    
    fault_source = Cy_SysFlt_GetErrorSource(FAULT_STRUCT0);

    if(fault_source != CY_SYSFLT_NO_FAULT)
    {
        /* Fault generated by System SRAM 0 non-correctable ECC error */
        if(fault_source == CY_SYSFLT_RAMC0_NC_ECC) // System SRAM 0 non-correctable ECC error
        {
            faultData0 = Cy_SysFlt_GetData0(FAULT_STRUCT0);
            faultData1 = Cy_SysFlt_GetData1(FAULT_STRUCT0);
            faultData2 = Cy_SysFlt_GetData2(FAULT_STRUCT0);
            faultData3 = Cy_SysFlt_GetData3(FAULT_STRUCT0);
        }

        /* Fault generated by System SRAM 0 correctable ECC error */
        if(fault_source == CY_SYSFLT_RAMC0_C_ECC) // System SRAM 0 correctable ECC error
        {
            faultData0 = Cy_SysFlt_GetData0(FAULT_STRUCT0);
            faultData1 = Cy_SysFlt_GetData1(FAULT_STRUCT0);
            faultData2 = Cy_SysFlt_GetData2(FAULT_STRUCT0);
            faultData3 = Cy_SysFlt_GetData3(FAULT_STRUCT0);
        } 
    }
    Cy_SysFlt_ClearInterrupt(FAULT_STRUCT0);
}

/* Application main
 *
 * This example shows the SRAM ecc injection use case:
 * 1. Two bit ECC error, get fault as non-correctable by hardware
 * 2. One bit ECC error, get fault as correctable error by hardware
 *
 **/
int main(void)
{
    SystemInit(); 
    
    /* Enable global interrupts. */
    __enable_irq();
    
    /* Enable CM4. CY_CORTEX_M4_APPL_ADDR is calculated in linker script, check it in case of problems. */
    Cy_SysEnableApplCore(CY_CORTEX_M4_APPL_ADDR); 

    /* Place your initialization/startup code here (e.g. MyInst_Start()) */
    Cy_GPIO_Pin_Init(USER_LED_PORT, USER_LED_PIN, &user_led_port_pin_cfg);
    
    /* Interrupt initialization for fault0 */
    {
        cy_stc_sysint_irq_t irq_cfg;
        irq_cfg = (cy_stc_sysint_irq_t){
            .sysIntSrc  = cpuss_interrupts_fault_0_IRQn,
            .intIdx     = CPUIntIdx2_IRQn,
            .isEnabled  = true,
        };
        Cy_SysInt_InitIRQ(&irq_cfg);
        Cy_SysInt_SetSystemIrqVector(cpuss_interrupts_fault_0_IRQn, irqFaultReport0Handler);
    }

    /* Enable the NVIC channel */
    NVIC_SetPriority(CPUIntIdx2_IRQn, 0);
    NVIC_ClearPendingIRQ(CPUIntIdx2_IRQn);
    NVIC_EnableIRQ(CPUIntIdx2_IRQn);

    /*********************** SRAM0, 2-bit Parity Error ************************/
    
    /* Clear status (typically this process is done by boot code) */
    Cy_SysFlt_ClearStatus(FAULT_STRUCT0);
    /* Enable Fault System SRAM 0 non-correctable ECC error */
    Cy_SysFlt_SetMaskByIdx(FAULT_STRUCT0, CY_SYSFLT_RAMC0_NC_ECC);
    /* Set interrupt mask for fault0 */
    Cy_SysFlt_SetInterruptMask(FAULT_STRUCT0);
    
    /* Configure the CPU for two bit parity error, with ECC injection */
    CPUSS->unRAM0_CTL0.stcField.u1ECC_EN = 1;
    CPUSS->unRAM0_CTL0.stcField.u1ECC_AUTO_CORRECT = 0;
    CPUSS->unRAM0_CTL0.stcField.u1ECC_INJ_EN = 1;
    CPUSS->unECC_CTL.stcField.u25WORD_ADDR = ((RAM_0_ADDRESS & RAM_0_MASK_VALUE) >> 2);
    CPUSS->unECC_CTL.stcField.u7PARITY = RAM_0_TWOBIT_PARITY;
    
    /* Write the data into SRAM */
    CY_SET_REG32(RAM_0_ADDRESS, RAM_0_DATA);
    
    /* Read the data from SRAM */
    CY_GET_REG32(RAM_0_ADDRESS);
    
    /* Wait for the fault trigger */
    while(!isr_triggered);
    
    /* Check for any error of fault trigger */
    if( (isr_triggered != 0) && (faultData0 != RAM_0_ADDRESS) && (fault_source != CY_SYSFLT_RAMC0_NC_ECC))
    {
        fail ++;
    }
    else
    {
        /* Clear the trigger flag */
        isr_triggered = 0;
        
        /* Clear the non-correctable fault interrupt mask */
        Cy_SysFlt_ClearMaskByIdx(FAULT_STRUCT0, CY_SYSFLT_RAMC0_NC_ECC);
    }
   
    /*********************** SRAM0, 1-bit Parity Error ************************/
    
    /* Clear status (typically this process is done by boot code) */
    Cy_SysFlt_ClearStatus(FAULT_STRUCT0);
    /* Enable Fault System SRAM 0 correctable ECC error */
    Cy_SysFlt_SetMaskByIdx(FAULT_STRUCT0, CY_SYSFLT_RAMC0_C_ECC);
    /* Set interrupt mask for fault0 */
    Cy_SysFlt_SetInterruptMask(FAULT_STRUCT0);
    
    /* Configure the CPU for one bit parity error, with ECC injection */
    CPUSS->unRAM0_CTL0.stcField.u1ECC_EN = 1;
    CPUSS->unRAM0_CTL0.stcField.u1ECC_AUTO_CORRECT = 0;
    CPUSS->unRAM0_CTL0.stcField.u1ECC_INJ_EN = 1;
    CPUSS->unECC_CTL.stcField.u7PARITY = RAM_0_ONEBIT_PARITY;
    
    /* Write the data into SRAM */
    CY_SET_REG32(RAM_0_ADDRESS, RAM_0_DATA);
    
    /* Read the data from SRAM */
    CY_GET_REG32(RAM_0_ADDRESS);
    
    /* Wait for the fault trigger */
    while(!isr_triggered);
    
    /* Clear the non-correctable fault interrupt mask */
    Cy_SysFlt_ClearMaskByIdx(FAULT_STRUCT0, CY_SYSFLT_RAMC0_C_ECC);
    
    /* Check for any error of fault trigger */
    if((isr_triggered != 0) && (faultData0 != RAM_0_ADDRESS) && (fault_source != CY_SYSFLT_RAMC0_C_ECC))
    {
        fail ++;
    }
    else
    {
        /* Clear the trigger flag */
        isr_triggered = 0;

        /* Clear the non-correctable fault interrupt mask */
        Cy_SysFlt_ClearMaskByIdx(FAULT_STRUCT0, CY_SYSFLT_RAMC0_C_ECC);
    }

    /* Configure the CPU for default settings */ 
    CPUSS->unRAM0_CTL0.stcField.u1ECC_AUTO_CORRECT = 1;
    CPUSS->unRAM0_CTL0.stcField.u1ECC_INJ_EN = 0;
    
    /* Check complete */    
    for(;;)
    {
        // Wait 0.05 [s]
        Cy_SysTick_DelayInUs(50000);
        Cy_GPIO_Inv(USER_LED_PORT, USER_LED_PIN);
    }
}


/* [] END OF FILE */
