/*******************************************************************************
* File Name: cycfg_seglcd.c
* Version 1.20
*
* Description:
* SegLCD display configuration
* This file should not be modified. It was automatically generated by
* Segment LCD Configurator 1.20.0.3158
*
********************************************************************************
* \copyright
* Copyright 2018-2021, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "cycfg_seglcd.h"

/* Set of common lines definition */
SegLCD_CONST_MODIFIER uint32_t SegLCD_commons[SegLCD_COM_NUM] =
{
    CY_SEGLCD_COMMON(SegLCD_COM_0,  0UL),
    CY_SEGLCD_COMMON(SegLCD_COM_1,  1UL),
    CY_SEGLCD_COMMON(SegLCD_COM_2,  2UL),
    CY_SEGLCD_COMMON(SegLCD_COM_3,  3UL),
};

/* Displays pixel array and structure definitions */

SegLCD_CONST_MODIFIER uint32_t SegLCD_Display0_pixMap[SegLCD_Display0_SYM_NUM][SegLCD_Display0_TYPE] =
{
    {
        CY_SEGLCD_PIXEL(SegLCD_SEG_0,  0UL), /* Display0_0_A */
        CY_SEGLCD_PIXEL(SegLCD_SEG_0,  2UL), /* Display0_0_B */
        CY_SEGLCD_NOT_CON,                   /* Display0_0_C */
        CY_SEGLCD_NOT_CON,                   /* Display0_0_D */
        CY_SEGLCD_NOT_CON,                   /* Display0_0_E */
        CY_SEGLCD_PIXEL(SegLCD_SEG_0,  1UL), /* Display0_0_F */
        CY_SEGLCD_PIXEL(SegLCD_SEG_0,  3UL), /* Display0_0_G */
    },
    {
        CY_SEGLCD_PIXEL(SegLCD_SEG_1,  0UL), /* Display0_1_A */
        CY_SEGLCD_PIXEL(SegLCD_SEG_1,  2UL), /* Display0_1_B */
        CY_SEGLCD_NOT_CON,                   /* Display0_1_C */
        CY_SEGLCD_NOT_CON,                   /* Display0_1_D */
        CY_SEGLCD_NOT_CON,                   /* Display0_1_E */
        CY_SEGLCD_PIXEL(SegLCD_SEG_1,  1UL), /* Display0_1_F */
        CY_SEGLCD_PIXEL(SegLCD_SEG_1,  3UL), /* Display0_1_G */
    },
    {
        CY_SEGLCD_PIXEL(SegLCD_SEG_2,  0UL), /* Display0_2_A */
        CY_SEGLCD_PIXEL(SegLCD_SEG_2,  2UL), /* Display0_2_B */
        CY_SEGLCD_NOT_CON,                   /* Display0_2_C */
        CY_SEGLCD_NOT_CON,                   /* Display0_2_D */
        CY_SEGLCD_NOT_CON,                   /* Display0_2_E */
        CY_SEGLCD_PIXEL(SegLCD_SEG_2,  1UL), /* Display0_2_F */
        CY_SEGLCD_PIXEL(SegLCD_SEG_2,  3UL), /* Display0_2_G */
    },
    {
        CY_SEGLCD_PIXEL(SegLCD_SEG_3,  0UL), /* Display0_3_A */
        CY_SEGLCD_PIXEL(SegLCD_SEG_3,  2UL), /* Display0_3_B */
        CY_SEGLCD_NOT_CON,                   /* Display0_3_C */
        CY_SEGLCD_NOT_CON,                   /* Display0_3_D */
        CY_SEGLCD_NOT_CON,                   /* Display0_3_E */
        CY_SEGLCD_PIXEL(SegLCD_SEG_3,  1UL), /* Display0_3_F */
        CY_SEGLCD_PIXEL(SegLCD_SEG_3,  3UL), /* Display0_3_G */
    },
};


SegLCD_CONST_MODIFIER cy_stc_seglcd_disp_t SegLCD_Display0 =
{
    .type   = SegLCD_Display0_TYPE,
    .symNum = SegLCD_Display0_SYM_NUM,
    .invert = false,
    .pixMap = (uint32_t*)SegLCD_Display0_pixMap,
    .font   = &cy_segLCD_7SegFont
};

/* [] END OF FILE */

